apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loadtestv2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtestv2
  minReplicas: 5
  maxReplicas: 2000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
